Vagrant::Config.run do |config|

  config.vm.box = "lucid64"
  config.vm.box_url = "http://files.vagrantup.com/lucid64.box"
  config.vm.share_folder "files", "/files", "files"
  config.vm.forward_port 8080, 1234
  config.vm.forward_port 27017, 27018

  config.vm.provision :puppet do |puppet|
    puppet.manifests_path = "manifests"
    puppet.manifest_file  = "solr.pp"
    puppet.module_path    = "../modules"
  end

end
